### ISSUE TITLE
"Verkürzungskollision"

### ISSUE THREAD

**Issue by dolonnen** [OleAlbers/shortener#1]
Ich habe vor ein paar Minuten folgende URL für 100 Tage verkürzen wollen:
http://www.rp-online.de/politik/correctiv-journalisten-verklagen-aussenministerium-wegen-mh17-absturz-aid-1.5014784

Herausgekommen ist: http://hurz.me/dP. Die zeigt auf https://wetransfer.com/downloads/06baaac008da354b25941f53ff41c3ed20170308134816/bbfa6e

Grüße
Markus Be

**Comment by Guacam-Ole** [comment]
Da sind tatsächlich zwei (fast zeitgleiche) nachfolgende  "verrutscht". Das sollte eigentlich nicht möglich sein. Muss da mal schauen, was da schief läuft.

**Comment by Guacam-Ole** [comment]
Ah. Manchmal ist die Lösung so nah. Kein Fehler in der Transaktion, lediglich die Zeichenfolge ..."MNPPQRS"... eingetragen für die Konvertierung, anstatt MN**O**PQRS :)

**Comment by dolonnen** [comment]
Lol. Ich liebe solche Fehler... :)

Danke

Ole Albers <notifications@github.com> schrieb am So., 12. März 2017, 22:20:
